### ISSUE TITLE
Broken script

### ISSUE THREAD

**Issue by vkhodygo** [Kron4ek/FAudio-Builds#1]
Hi

First of all, thank you for your work! It seems that it can fix some of the issues we have.

However, your script doesn't work when I run it on my Mint desktop.
One problem is that there is no "winedump" package (it has a slightly different name though). 
Second is somehow related to broken links (it seems that proton has only 64bit versions of the libraries, all 32bit versions are just links), therefore your script doesn't work like expected. 

Sincerely, 
V.

**Comment by Kron4ek** [comment]
Thank you for the report. I rewrote installation script and now it should perform without problems. Please, check if it works correctly now.

**Comment by vkhodygo** [comment]
Hey, thanks, now it works fine. Nevertheless, I still have problems with the sound after any load screen. Basically, I can hear only ambient (quiet) music, no other sounds. I have to restart the game to fix this. Any ideas?

**Comment by Kron4ek** [comment]
> Nevertheless, I still have problems with the sound after any load screen. Basically, I can hear only ambient (quiet) music, no other sounds.

I don't know. Probably, it's a bug of MinGW FAudio build. Or maybe it doesn't work correctly with Proton.

Btw, I saw your comment on Proton repo. Check if you have ffmpeg and libavcodec-dev installed during FAudio compilation (with -DFFMPEG=ON). If they are not installed, there will be no voices in Skyrim SE.

p.s. I [tested](https://youtu.be/_VGEUIPlODg) Skyrim SE with FAudio dlls on Wine-Staging and there was no such issue, so looks like it occurs only on Proton.

**Comment by vkhodygo** [comment]
This is some weird magic. Even with ffmpeg support still no music & speech. OK, thanks anyway.
