### ISSUE TITLE
Questions about FAudio

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/FAudio-Builds#3]
I have some questions about Faudio

1- I use your FAudio builds to be able to use FAudio, but a few games produces no sound at all when using it, so I decided to stop using it.

2- I heard that FAudio is part of Wine since version 4.3, but I use Kubuntu 19.04, and FAudio dependencies can only be installed from external repository https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport (I am not sure if that is still the case or not)
and I don't know what do I need to install from this repoistory, because the information in the internet about it is so confusing.

3- The developer of FAudio doesn't provide any support for these builds, and he just close any issues related to them, and the last time I tried to reach him, he blocked me form posting any thing in his github page, so I am confused, and pissed off at the same time, and I don't know what is the point of using it anyway!

**Comment by Kron4ek** [comment]
1. Probably MinGW builds of FAudio are less functional than native library (libFAudio.so). And seems like 32-bit builds are broken, maybe i will remove them soon.
2. I suppose it's necessary to install at least faudio, libsdl2 and ffmpeg.
3. Well, i think the reason is that my builds are unofficial and the developer can't be sure in their integrity.

**Comment by Ahmed-E-86** [comment]
1- You are totally right. 32bit games are the game that have issues.
2- Libsdl2 is installed as a dependency for Wine, ffmpeg is installed as well, and when I search for FAudio, I find these files, and I don't know what should I install exactly

![Faudio](https://user-images.githubusercontent.com/29783425/59133181-79421c00-8977-11e9-87e3-185856a9e611.png)

3- I don't know, he didn't even give me a change!

**Comment by Kron4ek** [comment]
> Libsdl2 is installed as a dependency for Wine

Be sure that libsdl2 is installed from the external repo, FAudio requires at least SDL2 2.0.9 and the main Ubuntu repo contains 2.0.8 version.

> I find these files, and I don't know what should I install exactly

According to the [packages list](http://ppa.launchpad.net/cybermax-dexter/sdl2-backport/ubuntu/pool/main/f/faudio/) of that repo libfaudio0 is FAudio 19.06, so you probably want to install libfaudio0. Other packages (libfaudio, libfaudio0-amd64 and libfaudio0-i386) are FAudio 19.03.

**Comment by Ahmed-E-86** [comment]
The installed version of libsdl2 is 2.0.9.

Thanks for answering my questions. Have a good day.
