### ISSUE TITLE
64-bit FAudio dlls not found!

### ISSUE THREAD

**Issue by alan-cugler** [Kron4ek/FAudio-Builds#5]
Hi, I found a guide for [Skyrim SE](https://www.reddit.com/r/linux_gaming/comments/byp2gc/skyrim_se_guide_with_mods_and_working_audio_steam/) and tried to do step 4 with your repository.
I ran 
```BASH
WINEPREFIX=$HOME/.steam/steam/steamapps/compatdata/489830/pfx ./wine_setup_faudio.sh
```
 I receive the following error:
```BASH
64-bit FAudio dlls not found!
Please, check if FAUDIO64_PATH is correct
```

Then looked at your scripts and realized you have the end-user run the `build_faudio_dlls.sh` script to get the dlls. However, I cant get the dependencies for `build_faudio_dlls.sh`, and was wondering how you get these dependencies:
- `mingw-w64-cmake`
- `mingw-w64-gcc`
- `mingw-w64-sdl2`
- `mingw-w64-ffmpeg`

I am running on ubuntu 18.04 and its default repositories only have: 
- `mingw-w64`
- `mingw-w64-common`
- `mingw-w64-i686-dev`
- `mingw-w64-tools`
- `mingw-w64-x86-64-dev`

Which installing all of these packages doesn't give me your unique dependencies listed.

When googling the internet for those dependencies I only get trash Windows related hits.

**Comment by Kron4ek** [comment]
> I receive the following error:
> 64-bit FAudio dlls not found!
> Please, check if FAUDIO64_PATH is correct

I suppose you cloned the repo (or downloaded master.zip), so dlls are missing. It's necessary to download .tar.xz archive from the [releases](https://github.com/Kron4ek/FAudio-Builds/releases) page.

> However, I cant get the dependencies for build_faudio_dlls.sh, and was wondering how you get these dependencies

Well, i use Arch and these dependencies can be installed from AUR in my case, but i can't help with obtaining these deps on Ubuntu, you'll probably need to compile them yourself.

**Comment by alan-cugler** [comment]
Thanks for the link to the releases page to get the tar. 
That was where I went wrong.
